#!/bin/bash
set -e

if [ -n "${GITEA_GID}" ]; then
    groupmod --gid "${GITEA_GID}" --non-unique git
fi

if [ -n "${GITEA_UID}" ]; then
    usermod --non-unique --uid "${GITEA_UID}" git
fi

if [ ! -f "${GITEA_WORK_DIR}"/custom/conf/app.ini ]; then
    mkdir -p "${GITEA_WORK_DIR}/custom/conf"
    dockerize -delims '⁅⁅:⁆⁆' -template /usr/local/share/gitea/conf/app.ini:"${GITEA_WORK_DIR}"/custom/conf/app.ini
    dockerize -delims '\u2045\u2045:\u2046\u2046' -template '{}:{}' -template /usr/local/share/gitea/conf/app.ini:"${GITEA_WORK_DIR}"/custom/conf/app.ini
fi

chown -R git:git "${GITEA_WORK_DIR}"
