#!/bin/sh
set -e -u -x

if [ ! -f "${GITEA_WORK_DIR}"/custom/conf/app.ini ]; then
    mkdir -p "${GITEA_WORK_DIR}/custom/conf"
    dockerize -template /usr/local/share/gitea/conf/app.ini:"${GITEA_WORK_DIR}"/custom/conf/app.ini
fi

chown -R git:git "${GITEA_WORK_DIR}"
